### ISSUE TITLE
Actividad 1 mates 

### ISSUE THREAD

**Issue by Kevin-bit-cm** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Kevin-bit-cm#1]
[DOC 1 mates .pdf](https://github.com/user-attachments/files/17382833/DOC.1.mates.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
